run_logged $ALETHEIA_INSTALL/packaging/base.sh
run_logged $ALETHEIA_INSTALL/packaging/aur.sh
run_logged $ALETHEIA_INSTALL/packaging/fonts.sh
run_logged $ALETHEIA_INSTALL/packaging/nvim.sh
run_logged $ALETHEIA_INSTALL/packaging/icons.sh
run_logged $ALETHEIA_INSTALL/packaging/webapps.sh
run_logged $ALETHEIA_INSTALL/packaging/tuis.sh
run_logged $ALETHEIA_INSTALL/packaging/custom-repo-replacements.sh
run_logged $ALETHEIA_INSTALL/packaging/official-apps.sh
run_logged $ALETHEIA_INSTALL/packaging/npx.sh
run_logged $ALETHEIA_INSTALL/packaging/asus-rog.sh
run_logged $ALETHEIA_INSTALL/packaging/framework16.sh
run_logged $ALETHEIA_INSTALL/packaging/surface.sh
